SELECT * FROM (
SELECT 575 AS mapid, 'boss_palehoof' AS sn
UNION ALL SELECT 575 AS mapid, 'boss_skadi' AS sn
UNION ALL SELECT 575 AS mapid, 'boss_skadi_grauf' AS sn
UNION ALL SELECT 575 AS mapid, 'boss_svala' AS sn
UNION ALL SELECT 575 AS mapid, 'boss_ymiron' AS sn
UNION ALL SELECT 578 AS mapid, 'boss_drakos' AS sn
UNION ALL SELECT 578 AS mapid, 'boss_eregos' AS sn
UNION ALL SELECT 578 AS mapid, 'boss_urom' AS sn
UNION ALL SELECT 578 AS mapid, 'boss_varos' AS sn
UNION ALL SELECT 595 AS mapid, 'boss_epoch' AS sn
UNION ALL SELECT 595 AS mapid, 'boss_infinite_corruptor' AS sn
UNION ALL SELECT 595 AS mapid, 'boss_mal_ganis' AS sn
UNION ALL SELECT 595 AS mapid, 'boss_meathook' AS sn
UNION ALL SELECT 595 AS mapid, 'boss_salramm' AS sn
UNION ALL SELECT 599 AS mapid, 'boss_krystallus' AS sn
UNION ALL SELECT 599 AS mapid, 'boss_maiden_of_grief' AS sn
UNION ALL SELECT 599 AS mapid, 'boss_sjonnir' AS sn
UNION ALL SELECT 599 AS mapid, 'boss_sjonnir_dwarf' AS sn
UNION ALL SELECT 599 AS mapid, 'boss_sjonnir_iron_sludge' AS sn
UNION ALL SELECT 599 AS mapid, 'boss_sjonnir_malformed_ooze' AS sn
UNION ALL SELECT 600 AS mapid, 'boss_dred' AS sn
UNION ALL SELECT 600 AS mapid, 'boss_tharon_ja' AS sn
UNION ALL SELECT 600 AS mapid, 'boss_trollgore' AS sn
UNION ALL SELECT 601 AS mapid, 'boss_krik_thir' AS sn
UNION ALL SELECT 604 AS mapid, 'boss_drakkari_colossus' AS sn
UNION ALL SELECT 604 AS mapid, 'boss_drakkari_elemental' AS sn
UNION ALL SELECT 604 AS mapid, 'boss_moorabi' AS sn
UNION ALL SELECT 604 AS mapid, 'boss_slad_ran' AS sn
UNION ALL SELECT 650 AS mapid, 'boss_black_knight' AS sn
UNION ALL SELECT 650 AS mapid, 'boss_eadric' AS sn
UNION ALL SELECT 650 AS mapid, 'boss_grand_champion' AS sn
UNION ALL SELECT 650 AS mapid, 'boss_paletress' AS sn
UNION ALL SELECT 658 AS mapid, 'boss_garfrost' AS sn
UNION ALL SELECT 658 AS mapid, 'boss_ick' AS sn
UNION ALL SELECT 658 AS mapid, 'boss_krick' AS sn
UNION ALL SELECT 658 AS mapid, 'boss_tyrannus' AS sn
UNION ALL SELECT 533 AS mapid, 'boss_faerlina' AS sn
UNION ALL SELECT 533 AS mapid, 'boss_four_horsemen' AS sn
UNION ALL SELECT 533 AS mapid, 'boss_gluth' AS sn
UNION ALL SELECT 533 AS mapid, 'boss_gothik' AS sn
UNION ALL SELECT 533 AS mapid, 'boss_grobbulus' AS sn
UNION ALL SELECT 533 AS mapid, 'boss_grobbulus_poison_cloud' AS sn
UNION ALL SELECT 533 AS mapid, 'boss_kelthuzad' AS sn
UNION ALL SELECT 533 AS mapid, 'boss_kelthuzad_minion' AS sn
UNION ALL SELECT 533 AS mapid, 'boss_loatheb' AS sn
UNION ALL SELECT 533 AS mapid, 'boss_maexxna' AS sn
UNION ALL SELECT 533 AS mapid, 'boss_maexxna_webwrap' AS sn
UNION ALL SELECT 533 AS mapid, 'boss_noth' AS sn
UNION ALL SELECT 533 AS mapid, 'boss_patchwerk' AS sn
UNION ALL SELECT 533 AS mapid, 'boss_razuvious' AS sn
UNION ALL SELECT 533 AS mapid, 'boss_razuvious_minion' AS sn
UNION ALL SELECT 533 AS mapid, 'boss_sapphiron' AS sn
UNION ALL SELECT 533 AS mapid, 'boss_thaddius' AS sn
UNION ALL SELECT 533 AS mapid, 'boss_thaddius_summon' AS sn
UNION ALL SELECT 649 AS mapid, 'boss_acidmaw' AS sn
UNION ALL SELECT 649 AS mapid, 'boss_anubarak_trial' AS sn
UNION ALL SELECT 649 AS mapid, 'boss_dreadscale' AS sn
UNION ALL SELECT 649 AS mapid, 'boss_eydis' AS sn
UNION ALL SELECT 649 AS mapid, 'boss_fjola' AS sn
UNION ALL SELECT 649 AS mapid, 'boss_gormok' AS sn
UNION ALL SELECT 649 AS mapid, 'boss_icehowl' AS sn
UNION ALL SELECT 649 AS mapid, 'boss_jaraxxus' AS sn
UNION ALL SELECT 624 AS mapid, 'boss_archavon' AS sn
UNION ALL SELECT 624 AS mapid, 'boss_emalon' AS sn
UNION ALL SELECT 624 AS mapid, 'boss_koralon' AS sn
UNION ALL SELECT 624 AS mapid, 'boss_toravon' AS sn
UNION ALL SELECT 631 AS mapid, 'boss_blood_queen_lana_thel' AS sn
UNION ALL SELECT 631 AS mapid, 'boss_deathbringer_saurfang' AS sn
UNION ALL SELECT 631 AS mapid, 'boss_festergut' AS sn
UNION ALL SELECT 631 AS mapid, 'boss_lady_deathwhisper' AS sn
UNION ALL SELECT 631 AS mapid, 'boss_prince_keleseth_icc' AS sn
UNION ALL SELECT 631 AS mapid, 'boss_prince_taldaram_icc' AS sn
UNION ALL SELECT 631 AS mapid, 'boss_prince_valanar_icc' AS sn
UNION ALL SELECT 631 AS mapid, 'boss_professor_putricide' AS sn
UNION ALL SELECT 631 AS mapid, 'boss_rotface' AS sn
UNION ALL SELECT 631 AS mapid, 'boss_sindragosa' AS sn
UNION ALL SELECT 631 AS mapid, 'boss_sister_svalna' AS sn
UNION ALL SELECT 631 AS mapid, 'boss_the_lich_king' AS sn
UNION ALL SELECT 631 AS mapid, 'boss_valithria_dreamwalker' AS sn
UNION ALL SELECT 724 AS mapid, 'boss_baltharus_the_warborn' AS sn
UNION ALL SELECT 724 AS mapid, 'boss_general_zarithrian' AS sn
UNION ALL SELECT 724 AS mapid, 'boss_halion' AS sn
UNION ALL SELECT 724 AS mapid, 'boss_saviana_ragefire' AS sn
UNION ALL SELECT 724 AS mapid, 'boss_twilight_halion' AS sn
) bm
