-- ---------------------------------------------------------------------------
-- mod-procedural-dungeon v2: map 760 'The Forgotten Depths' (world database)
--
-- GENERATED by ForgottenLand2.0/scripts/47_pd_map760_rows.py from the same
-- values it writes into the client DBCs - do not edit by hand, or the two
-- sides drift and the client and server disagree about what map 760 is.
--
-- PDv2 keeps NO terrain files for this map on the server: heights come from
-- nowhere, the area comes from MapEntry.linked_zone (5100) and movement runs
-- on the module's own walk grid. So no extractor run is needed for 760.
-- ---------------------------------------------------------------------------

-- Mandatory: MapInstanced::CreateInstance ABORTs without it, and
-- MapMgr::IsValidMAP rejects a teleport to a dungeon map that has no row.
DELETE FROM `instance_template` WHERE `map` = 760;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES
(760, 0, '', 1);

DELETE FROM `map_dbc` WHERE `ID` = 760;
INSERT INTO `map_dbc` (`ID`, `Directory`, `InstanceType`, `Flags`, `PVP`, `MapName_Lang_enUS`, `MapName_Lang_enGB`, `MapName_Lang_koKR`, `MapName_Lang_frFR`, `MapName_Lang_deDE`, `MapName_Lang_enCN`, `MapName_Lang_zhCN`, `MapName_Lang_enTW`, `MapName_Lang_zhTW`, `MapName_Lang_esES`, `MapName_Lang_esMX`, `MapName_Lang_ruRU`, `MapName_Lang_ptPT`, `MapName_Lang_ptBR`, `MapName_Lang_itIT`, `MapName_Lang_Unk`, `MapName_Lang_Mask`, `AreaTableID`, `MapDescription0_Lang_enUS`, `MapDescription0_Lang_enGB`, `MapDescription0_Lang_koKR`, `MapDescription0_Lang_frFR`, `MapDescription0_Lang_deDE`, `MapDescription0_Lang_enCN`, `MapDescription0_Lang_zhCN`, `MapDescription0_Lang_enTW`, `MapDescription0_Lang_zhTW`, `MapDescription0_Lang_esES`, `MapDescription0_Lang_esMX`, `MapDescription0_Lang_ruRU`, `MapDescription0_Lang_ptPT`, `MapDescription0_Lang_ptBR`, `MapDescription0_Lang_itIT`, `MapDescription0_Lang_Unk`, `MapDescription0_Lang_Mask`, `MapDescription1_Lang_enUS`, `MapDescription1_Lang_enGB`, `MapDescription1_Lang_koKR`, `MapDescription1_Lang_frFR`, `MapDescription1_Lang_deDE`, `MapDescription1_Lang_enCN`, `MapDescription1_Lang_zhCN`, `MapDescription1_Lang_enTW`, `MapDescription1_Lang_zhTW`, `MapDescription1_Lang_esES`, `MapDescription1_Lang_esMX`, `MapDescription1_Lang_ruRU`, `MapDescription1_Lang_ptPT`, `MapDescription1_Lang_ptBR`, `MapDescription1_Lang_itIT`, `MapDescription1_Lang_Unk`, `MapDescription1_Lang_Mask`, `LoadingScreenID`, `MinimapIconScale`, `CorpseMapID`, `CorpseX`, `CorpseY`, `TimeOfDayOverride`, `ExpansionID`, `RaidOffset`, `MaxPlayers`) VALUES
(760, 'FLPD', 1, 0, 0, 'The Forgotten Depths', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 5100, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712188, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712188, 142, 1.0, -1, -11207.798828125, 1681.15087890625, -1, 2, 0, 5);

-- Without a MapDifficulty row the CLIENT refuses entry outright, and the
-- server's MapMgr::PlayerCannotEnter returns DIFFICULTY_UNAVAILABLE.
DELETE FROM `mapdifficulty_dbc` WHERE `MapID` = 760;
INSERT INTO `mapdifficulty_dbc` (`ID`, `MapID`, `Difficulty`, `Message_Lang_enUS`, `Message_Lang_enGB`, `Message_Lang_koKR`, `Message_Lang_frFR`, `Message_Lang_deDE`, `Message_Lang_enCN`, `Message_Lang_zhCN`, `Message_Lang_enTW`, `Message_Lang_zhTW`, `Message_Lang_esES`, `Message_Lang_esMX`, `Message_Lang_ruRU`, `Message_Lang_ptPT`, `Message_Lang_ptBR`, `Message_Lang_itIT`, `Message_Lang_Unk`, `Message_Lang_Mask`, `RaidDuration`, `MaxPlayers`, `Difficultystring`) VALUES
(857, 760, 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 5, '');

-- One row per theme:
--   5100 = theme 2 'The Forgotten Depths', ambience 37, music 439
--   5101 = theme 1 'The Forgotten Mine', ambience 34, music 236
--   5102 = theme 3 'The Forgotten Woods', ambience 35, music 1
-- 5100 is the area the whole map falls back to; see linked_zone above. The
-- other two are CLIENT-side ids the composer stamps into the MCNK headers,
-- and the server never answers them - they are shipped here only so this
-- file's client-against-server check stays a real diff. AreaBit 4007 is this
-- dungeon's own exploration bit, shared by all three because exploration
-- runs off the server area, which is always 5100.
DELETE FROM `areatable_dbc` WHERE `ID` IN (5100, 5101, 5102);
INSERT INTO `areatable_dbc` (`ID`, `ContinentID`, `ParentAreaID`, `AreaBit`, `Flags`, `SoundProviderPref`, `SoundProviderPrefUnderwater`, `AmbienceID`, `ZoneMusic`, `IntroSound`, `ExplorationLevel`, `AreaName_Lang_enUS`, `AreaName_Lang_enGB`, `AreaName_Lang_koKR`, `AreaName_Lang_frFR`, `AreaName_Lang_deDE`, `AreaName_Lang_enCN`, `AreaName_Lang_zhCN`, `AreaName_Lang_enTW`, `AreaName_Lang_zhTW`, `AreaName_Lang_esES`, `AreaName_Lang_esMX`, `AreaName_Lang_ruRU`, `AreaName_Lang_ptPT`, `AreaName_Lang_ptBR`, `AreaName_Lang_itIT`, `AreaName_Lang_Unk`, `AreaName_Lang_Mask`, `FactionGroupMask`, `LiquidTypeID_1`, `LiquidTypeID_2`, `LiquidTypeID_3`, `LiquidTypeID_4`, `MinElevation`, `Ambient_Multiplier`, `Lightid`) VALUES
(5100, 760, 0, 4007, 0, 76, 0, 37, 439, 551, 0, 'The Forgotten Depths', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 2, 0, 0, 0, 0, -500.0, 0.0, 0),
(5101, 760, 0, 4007, 0, 76, 0, 34, 236, 0, 0, 'The Forgotten Mine', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 2, 0, 0, 0, 0, -500.0, 0.0, 0),
(5102, 760, 0, 4007, 0, 76, 0, 35, 1, 0, 0, 'The Forgotten Woods', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 2, 0, 0, 0, 0, -500.0, 0.0, 0);

-- The lights. The server reads ID/ContinentID/X/Y/Z only, and it reads them
-- for exactly one thing: GetDefaultMapLight(760) scans DESCENDING and returns
-- the first row of this map whose position is all zero, which is the id every
-- SMSG_OVERRIDE_LIGHT packet carries as the light to fall back to. With
-- light_dbc empty that id is 0, and a client told to fall back to light 0
-- has nothing to fall back to. 2863 is that row, and it is the CITY's light by
-- the same token: the map default is what applies wherever no positioned
-- light reaches. The other rows ARE positioned, one per theme region -
-- SMSG_OVERRIDE_LIGHT is ignored by the 3.3.5a client, so the client picks
-- them up by camera position instead:
--   2864 = theme 1, origin block (256,272) = tile (32,34), window centre (-1333.33, -266.67) yd, falloff 450/520 yd
--   2865 = theme 3, origin block (256,240) = tile (32,30), window centre (800.00, -266.67) yd, falloff 450/520 yd
-- The X/Y/Z column names are AzerothCore's own and are nominal: the DBC
-- fields behind them are (17066.66656 - worldY) x 36, worldZ x 36 and
-- (17066.66656 - worldX) x 36 - measured, see script 47. The core only ever
-- tests them for all-zero, so the naming costs it nothing.
DELETE FROM `light_dbc` WHERE `ID` IN (2863, 2864, 2865);
INSERT INTO `light_dbc` (`ID`, `ContinentID`, `X`, `Y`, `Z`, `FalloffStart`, `FalloffEnd`, `LightParamsID_1`, `LightParamsID_2`, `LightParamsID_3`, `LightParamsID_4`, `LightParamsID_5`, `LightParamsID_6`, `LightParamsID_7`, `LightParamsID_8`) VALUES
(2863, 760, 0.0, 0.0, 0.0, 0.0, 0.0, 918, 918, 918, 918, 4, 0, 0, 0),
(2864, 760, 624000.0, 1800.0, 662400.0, 16200.0, 18720.0, 919, 919, 919, 919, 4, 0, 0, 0),
(2865, 760, 624000.0, 1800.0, 585600.0, 16200.0, 18720.0, 920, 920, 920, 920, 4, 0, 0, 0);

-- NOT done here: removing v1's map-37 override. mod_pdungeon_base.sql still
-- INSERTs those rows, so deleting them from this file would only work
-- because 'base' sorts before 'map760' - and it would break v1, which has
-- to keep running until the engine glue replaces it. The cleanup belongs in
-- the commit that deletes PDWorldBuilder. An unused instanced Azshara Crater
-- is harmless in the meantime.
