-- mod-procedural-dungeon: prop GameObject displays + templates.
-- GENERATED by scripts/57_pd_prop_displays.py - do not edit by hand.
--
-- Massive props are SERVER GameObjects because MDDF doodads have no
-- player collision on this client (measured in the first Phase-4 T2
-- round; the brazier - a type-5 GO - was the only thing that collided).
-- M2 displays keep the props LoS-inert server-side, so the walk grid
-- stays the only navigation truth. Placement comes from the kit's
-- per-variant prop anchors (pdungeon_chunk_meta.anchors, key 'props').

-- The one display this client lacks: the Stormwind fountain.
-- Server side = the gameobjectdisplayinfo_dbc OVERRIDE table (the
-- mechanism Turtle's 222 rows already use); the matching client row
-- ships in patch-9 (hot_dbc staging, script 30).
DELETE FROM `gameobjectdisplayinfo_dbc` WHERE `ID` = 92040;
INSERT INTO `gameobjectdisplayinfo_dbc` (`ID`, `ModelName`, `GeoBoxMinX`, `GeoBoxMinY`, `GeoBoxMinZ`, `GeoBoxMaxX`, `GeoBoxMaxY`, `GeoBoxMaxZ`) VALUES
(92040, 'World\\GENERIC\\HUMAN\\PASSIVE DOODADS\\Fountains\\StormwindFountain01.mdx', -5.03, -4.99, -0.26, 5.04, 5.08, 9.43);

-- The templates. The DELETE names each entry (never a range) so this
-- file speaks for exactly these ids - same discipline as the decor SQL.
DELETE FROM `gameobject_template` WHERE `entry` IN (910040, 910041, 910042, 910043, 910044, 910045, 910046, 910047);
INSERT INTO `gameobject_template` (`entry`, `type`, `displayId`, `name`, `size`, `Data0`, `Data1`, `ScriptName`) VALUES
(910040, 5, 92040, 'PD Fountain', 1, 0, 0, ''),
(910041, 5, 5073, 'PD Rock Column', 1.7, 0, 0, ''),
(910042, 5, 5073, 'PD Stalagmite', 1, 0, 0, ''),
(910043, 5, 2230, 'PD Cave-In', 0.4, 0, 0, ''),
(910044, 5, 6961, 'PD Broken Cart', 1, 0, 0, ''),
(910045, 5, 251, 'PD Haystack', 1.2, 0, 0, ''),
(910046, 5, 2890, 'PD Sack Pile', 1, 0, 0, ''),
(910047, 5, 150, 'PD Signpost', 1, 0, 0, '');
