-- ---------------------------------------------------------------------------
-- mod-procedural-dungeon v2: map 760 'The Forgotten Depths' (world database)
--
-- GENERATED by ForgottenLand2.0/scripts/47_pd_map760_rows.py from the same
-- values it writes into the client DBCs - do not edit by hand, or the two
-- sides drift and the client and server disagree about what map 760 is.
--
-- PDv2 keeps NO terrain files for this map on the server: heights come from
-- nowhere, the area comes from MapEntry.linked_zone (5100) and movement runs
-- on the module's own walk grid. So no extractor run is needed for 760.
-- ---------------------------------------------------------------------------

-- Mandatory: MapInstanced::CreateInstance ABORTs without it, and
-- MapMgr::IsValidMAP rejects a teleport to a dungeon map that has no row.
DELETE FROM `instance_template` WHERE `map` = 760;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES
(760, 0, '', 1);

DELETE FROM `map_dbc` WHERE `ID` = 760;
INSERT INTO `map_dbc` (`ID`, `Directory`, `InstanceType`, `Flags`, `PVP`, `MapName_Lang_enUS`, `MapName_Lang_Mask`, `AreaTableID`, `MapDescription0_Lang_Mask`, `MapDescription1_Lang_Mask`, `LoadingScreenID`, `MinimapIconScale`, `CorpseMapID`, `CorpseX`, `CorpseY`, `TimeOfDayOverride`, `ExpansionID`, `RaidOffset`, `MaxPlayers`) VALUES
(760, 'FLPD', 1, 0, 0, 'The Forgotten Depths', 16712190, 5100, 0, 0, 0, 1, -1, 0, 0, -1, 2, 0, 5);

-- Without a MapDifficulty row the CLIENT refuses entry outright, and the
-- server's MapMgr::PlayerCannotEnter returns DIFFICULTY_UNAVAILABLE.
DELETE FROM `mapdifficulty_dbc` WHERE `MapID` = 760;
INSERT INTO `mapdifficulty_dbc` (`ID`, `MapID`, `Difficulty`, `Message_Lang_Mask`, `RaidDuration`, `MaxPlayers`, `Difficultystring`) VALUES
(857, 760, 0, 0, 0, 5, '');

-- The area the whole map falls back to; see linked_zone above.
DELETE FROM `areatable_dbc` WHERE `ID` = 5100;
INSERT INTO `areatable_dbc` (`ID`, `ContinentID`, `ParentAreaID`, `AreaBit`, `Flags`, `ExplorationLevel`, `AreaName_Lang_enUS`, `AreaName_Lang_Mask`) VALUES
(5100, 760, 0, 0, 0, 80, 'The Forgotten Depths', 16712190);

-- NOT done here: removing v1's map-37 override. mod_pdungeon_base.sql still
-- INSERTs those rows, so deleting them from this file would only work
-- because 'base' sorts before 'map760' - and it would break v1, which has
-- to keep running until the engine glue replaces it. The cleanup belongs in
-- the commit that deletes PDWorldBuilder. An unused instanced Azshara Crater
-- is harmless in the meantime.
